FROM node:14.20.0

ENV INSTALL_PATH /app
RUN mkdir -p $INSTALL_PATH

WORKDIR $INSTALL_PATH
COPY ./package.json .
RUN npm install

COPY . .

ARG REACT_APP_COTIPAY_URL
RUN echo "REACT_APP_COTIPAY_URL:" $REACT_APP_COTIPAY_URL
ENV REACT_APP_COTIPAY_URL $REACT_APP_COTIPAY_URL

ARG REACT_APP_COTI_URL
RUN echo "REACT_APP_COTI_URL:" $REACT_APP_COTI_URL
ENV REACT_APP_COTI_URL $REACT_APP_COTI_URL

ARG REACT_APP_HOST
RUN echo "REACT_APP_HOST:" $REACT_APP_HOST
ENV REACT_APP_HOST $REACT_APP_HOST

ARG REACT_APP_CHAIN_ID
RUN echo "REACT_APP_CHAIN_ID:" $REACT_APP_CHAIN_ID
ENV REACT_APP_CHAIN_ID $REACT_APP_CHAIN_ID

ARG REACT_APP_ENVIRONMENT
RUN echo "REACT_APP_ENVIRONMENT:" $REACT_APP_ENVIRONMENT
ENV REACT_APP_ENVIRONMENT $REACT_APP_ENVIRONMENT

ARG REACT_APP_NETWORK_URL
RUN echo "REACT_APP_NETWORK_URL:" $REACT_APP_NETWORK_URL
ENV REACT_APP_NETWORK_URL $REACT_APP_NETWORK_URL

ARG GENERATE_SOURCEMAP
RUN echo "GENERATE_SOURCEMAP:" $GENERATE_SOURCEMAP
ENV GENERATE_SOURCEMAP $GENERATE_SOURCEMAP

RUN npm run build

RUN if [ "$NODE_ENV" = "production" ]; then rm -r build/static/*/*.map ; fi

# RUN npm install -g serve

CMD ["node","server.js"]
