// APP //
export const ADD_ALERT = 'ADD_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
export const SET_SELECT_NETWORK = 'SET_SELECT_NETWORK';
export const SET_NETWORK_STATUS = 'SET_NETWORK_STATUS';
export const SET_MIGRATION_MODAL_IS_OPEN = 'SET_MIGRATION_MODAL_IS_OPEN';
export const SET_GOVI_MIGRATION_MODAL_IS_OPEN = "SET_GOVI_MIGRATION_MODAL_IS_OPEN";

// CVI
export const SET_VOL_INFO = "SET_VOL_INFO"; 
export const UPDATE_VOL_INFO = "UPDATE_VOL_INFO"; 

// WALLET 
export const SET_DATA = 'SET_DATA';

//EVENTS
export const ADD_EVENT = 'ADD_EVENT';
export const ACTION_CONFIRMED = 'ACTION_CONFIRMED';